---
- name: create folders for virtualenv
  raw: mkdir -p ~/{bin,tmp,lib/python3.4}

- name: install pip
  easy_install:
    executable: easy_install-3.4
    name: pip
    state: latest

- name: install virtualenv
  raw: ~/bin/pip3.4 install virtualenv 

- name: install virtualenvwrapper
  raw: ~/bin/pip3.4 install --install-option="--user" virtualenvwrapper

- name: add virtualenvwrapper exports to .bash_profile
  lineinfile: 'dest=~/.bash_profile line="{{ item }}"'
  with_items:
    - export PATH=$PATH:$HOME/bin
    - export TMPDIR=$HOME/tmp
    - export WORKON_HOME=$HOME/Envs
    - export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3.4
    - export PIP_VIRTUALENV_BASE=$WORKON_HOME
    - export PIP_RESPECT_VIRTUALENV=true
    - source $HOME/bin/virtualenvwrapper.sh

- name: source the new .bash_profile
  raw: source .bashrc