---
- name: Create Stage on the Webfaction and add wordpress
  hosts: target1
  vars:
    active_symlink: false
  vars_files:
   - vars/external_vars.yml
  
  roles:
   - mysql
   - domains
   - php72
   - website
   - wordpress