---
- name: Create Stage on the Webfaction and add Laravel 6
  hosts: target1
  vars:
    active_symlink: true
  vars_files:
   - vars/external_vars.yml
  
  roles:
   - mysql
   - domains
   - php72
   - symlink
   - website
   - laravel
  